### ISSUE TITLE
lightgallery has problem with dom elements

### ISSUE THREAD

**Issue by Phoenix404** [sachinchoolur/lightGallery#259] opened 2015-12-15 20:08 UTC
Lightgallery has problem with dom elements. see here http://jsfiddle.net/d15zp2Lc/ http://jsfiddle.net/6oun2u2w/  updated http://jsfiddle.net/6oun2u2w/1/

This fiddle (http://jsfiddle.net/6oun2u2w/) is working  when image is in html code .

This fiddle (http://jsfiddle.net/d15zp2Lc/ ) is not working if i call image with js ...
please check and tell me how can i do with js or dom?

**Comment by kursusHC** [comment] 2015-12-16 08:31
Lightgallery has no "problem with DOM elements". Your last fiddle doesn't work because you're calling Lightgallery on .continer right on load, before it even exists in the DOM ! Put the init call anywhere where .continer is loaded and it works, see here : http://jsfiddle.net/nuLyryue/

**Comment by Phoenix404** [comment] 2015-12-16 12:45
hwo to to that ?

**Comment by kursusHC** [comment] 2015-12-16 14:10
By reading the linked example. Please close your issue.

**Comment by Phoenix404** [comment] 2015-12-16 16:54
Uncaught TypeError: Cannot read property 'match' of undefined.. i am getting this error sometimes not always why ? i upload only images png or jpg jpeg.. i have uploaded only extentions and this give me this error and lighgallery show only loading gif..

**Comment by Phoenix404** [comment] 2015-12-16 17:03
here i uploaded an images
code image 
![pasted_image1](https://cloud.githubusercontent.com/assets/13603818/11847743/2f87766e-a41f-11e5-9650-6782a2e10b4b.png)

and error image
![pasted_image](https://cloud.githubusercontent.com/assets/13603818/11847761/4957df7a-a41f-11e5-8f24-95f9880b07ff.png)

**Comment by Phoenix404** [comment] 2015-12-16 17:29
there is 6 photos and lightgallery show 7

**Comment by kursusHC** [comment] 2015-12-16 23:41
This doesn't seem like a lightgallery problem, this question would be more suited in a general forum. In any case please learn to ask for help properly, it will help you to get useful answers. 

- 1 thread = 1 subject. Your original problem seems solved so you can close this issue, this will keep the project clean. 
- Image code is not an option, post a jsfiddle reproducing the problem.
- People like words like hello and thanks.

About what you posted, you should know that using setTimeout is most of the time a bad idea. You never now what will be the state of your code after X seconds on your users' computers. It can lead to weird problem like yours, dig this way.

**Closed** 2015-12-17 15:26 UTC
