### ISSUE TITLE
Lightbox to be Overlayed On Top of Navigation Bar

### ISSUE THREAD

**Issue by larrybyeo** [sachinchoolur/lightGallery#260] opened 2015-12-17 06:54 UTC
Hello,

Terrific plugin, I love it!  I have one issue though; right now, my navigation bar on my website is currently set to the max z-index to ensure that it stays on top of the whole page.  However, I would like it so that when the lightbox slider goes to full screen mode, the navigation bar will go under it.  Do you know where in your css file I can set the z-index so that the whole lightbox will overlay on top of the navigation bar?  Thank you so much!

**Comment by kursusHC** [comment] 2015-12-17 09:44
Hi, 

A few things : 

- Setting z-index kind of randomly on your site just "to ensure" is a bad practice, you get why now. Better test all the overlays on your site and check what conflicts.  

- "maximum z-index" is known to be 16777271 in Safari 3 and 2147483647 on every single other browsers (even IE6), so I guess you still have room ;) 

- For slight modifications like this, never modify the original css, it would prevent you from updating properly. Better add it to your own css. 

- Tools like Firebug or Developper Tools are very handy to get the kind of information you're looking for. 

- Elements that rules z-index of Lightgallery are .lg-backdrop and .lg-outer, they are by default respectively set to 1040 and 1050. So you can override them in your CSS like : 

```
.lg-backdrop {z-index: 10040;}
.lg-outer {z-index: 10050;}
```

Finally sometimes overriding CSS doesn't seem to work, that is because of specificity, you can read [this article](https://css-tricks.com/specifics-on-css-specificity/) to understand it.

**Comment by kursusHC** [comment] 2015-12-17 10:50
What you could do is bind a click event to the fullscreen button and set css accordingly (untested but you get the idea): 

```
$('body').on('click', '.lg-outer:not(.lg-fullscreen-on) .lg-fullscreen', function() {
$('.lg-backdrop').css('z-index', 10040);
$('.lg-outer').css('z-index', 10050);
});


$('body').on('click', '.lg-outer.lg-fullscreen-on .lg-fullscreen', function() {
// Back to default values
$('.lg-backdrop').css('z-index', 1040);
$('.lg-outer').css('z-index', 1050);
});
```

You could work with addClass() and removeClass() instead of setting CSS with jQuery, it would be more elegant.

**Comment by larrybyeo** [comment] 2015-12-18 00:35
Hey kurusus, thanks for your reply.  I am trying to use the addClass() and removeClass() methods to do this, and right now, I have the removeClass portion working:

$('.js--click-header-image').click(function () {
        var nav = $('nav');
        $('nav').removeClass('sticky');  
    })

Where the '.js--click-header-image' is equivalent to 'body' and the 'sticky' class controls the navigation.  Now I want to add the class back in when I click outside the picture or press the close button.  Do you know which particular classes I would need to call, and how I would do it to bring the class back in once I exit the LightGallery?  Thanks!

**Comment by kursusHC** [comment] 2015-12-18 09:23
Why don't you take it the other way, the one I showed you ? This would be a far more reliable mean to detect gallery opening and closing. 

Say your `header` has a z-index of 2000. Lightgallery has a 1040 and 1050 z-index, so you need to set them higher in order to cover it.

In Lightgallery CSS you have : 

```
.lg-backdrop {z-index:1040;}
.lg-outer {z-index:1050;}
```

Just add a new rule in your own css : 

```
.lg-backdrop.fullscreen {z-index:3040;}
.lg-outer.fullscreen {z-index:3050;}
```

Now you just have to add the `fullscreen` class to these elements when you need it, and they will go above your header : 

```
// Fullscreen button is clicked when gallery is not fullscreen 
$('body').on('click', '.lg-outer:not(.lg-fullscreen-on) .lg-fullscreen', function() {
  $('.lg-backdrop').addClass('fullscreen');
  $('.lg-outer').addClass('fullscreen');
});

// Fullscreen button is clicked when gallery is already fullscreen 
$('body').on('click', '.lg-outer.lg-fullscreen-on .lg-fullscreen', function() {
  // Back to default values
  $('.lg-backdrop').removeClass('fullscreen');
  $('.lg-outer').removeClass('fullscreen');
});
```

If this doesn't solve the problem post a JSFiddle reproducing the problem. By the way jQuery `.click()` is deprecated, use `.on()` instead.

**Comment by larrybyeo** [comment] 2015-12-21 05:10
Thanks kursus, once again, for your help.  I actually ended up just decreasing the z-index value on my navigation bar to a value that is lower than 1040, and that seemed to do the trick.  I actually just posted up another issue, so if you could provide your assistance on that, then that'd be awesome: https://github.com/sachinchoolur/lightGallery/issues/268.  Thanks!

**Comment by kursusHC** [comment] 2015-12-21 10:20
Ok great, if you consider your issue fixed please close it.

**Closed** 2015-12-22 01:02 UTC
