### ISSUE TITLE
Zoom behaviour on mobile devices 

### ISSUE THREAD

**Issue by mariorudloff** [sachinchoolur/lightGallery#406] opened 2016-07-28 14:20 UTC
The issue described in #182 appears on mobile devices as well.
We saw this behaviour on two devices:
- Safari on iPhone SE with iOS 9.3.2
- Stock Android Browser on LG G2 (D802) with Android 5.0.2

I suspect this to happen due to the separation of the scale and position transitions between two different DOM nodes. The fix could be to simply scale and move the image at once instead of scaling the image and moving the container.

Please see the attached screen recording:

![ezgif-2948147132](https://cloud.githubusercontent.com/assets/17177495/17215549/8a30fcec-54dd-11e6-8e0d-158a5931039c.gif)

**Comment by francishutchings** [comment] 2016-09-01 13:25
Does anyone have a solution for this issue?

**Comment by Shaker-Hamdi** [comment] 2016-09-06 11:49
Still waiting for a fix for this issue.

**Comment by abnersajr** [comment] 2016-09-06 14:09
I will see what is happening when I have some time. Probably this weekend I will try to see if I can fix this. If more peoples can submit your experiences with images or screen recorder it would be nice.

**Comment by Shaker-Hamdi** [comment] 2016-09-26 10:12
Any updates on this issue?
It's really unpleasant effect.

**Comment by sachinchoolur** [comment] 2016-09-26 10:23
Hi Guys,
The issue has already been fixed. Which version of lightgallery you are using?

**Comment by Shaker-Hamdi** [comment] 2016-09-26 10:39
I'm using the latest version 1.3.2, and the problem still exist.
Please note that this behavior only happens in iPhones, it doesn't exist on my Android device.

**Comment by sachinchoolur** [comment] 2016-09-26 10:52
Hi @Shaker-Hamdi,
Thanks for the clarification. It's because of the poor CSS3 animation performance on iPhone. 
Anyway, I'll ty to find a solution

**Comment by Shaker-Hamdi** [comment] 2016-09-26 11:16
Thanks @sachinchoolur for the reply.
I did suspect the issue to be related to CSS3 performance on iPhone, I tried to add the "-webkit-perspective: 1000;" trick, but with no luck.

**Comment by makshh** [comment] 2016-09-26 12:05
I think it is related to the fact that you also change left and top values on the parent element (when I changed left and top to translateX and Y there is no flickering on iOS).

**Comment by Shaker-Hamdi** [comment] 2016-09-26 12:09
@makshh, could you please provide a code example of what values are you changing exactly?

**Comment by makshh** [comment] 2016-09-26 12:20
```
$image.parent().css({
  left: -x + 'px',
  top: -y + 'px'
}).attr('data-x', x).attr('data-y', y);

```
Changed to:

```
$image.parent().css({
  transform: 'translate(' + -x + 'px, ' + -y + 'px)'
}).attr('data-x', x).attr('data-y', y);
```



But it doesn't fix the whole problem, I changed this only to see what happens on iOS

**Comment by Shaker-Hamdi** [comment] 2016-09-26 13:53
@makshh, That did fixed it on iPhone, but the behavior is now on Android and the Desktop :smile:

**Comment by makshh** [comment] 2016-09-26 14:12
@Shaker-Hamdi, you are right, very strange :), maybe solution is to use left and top and transform only for iOS? ;)

**Comment by sachinchoolur** [comment] 2016-09-26 14:38
Previously I was using translate instead of top and left, and I had the issue on desktop firefox and chrome.
I think @makshh's solution would be fine. We can detect iPhone and apply translate instead of top and left.
I don't have an iPhone to test this. Any help with this issue would be much appreciated.

**Comment by Shaker-Hamdi** [comment] 2016-09-26 15:16
I edited the code in @makshh gist, and start checking for iPad, iPhone and iPod ...

```
var iOS = /iPad|iPhone|iPod/.test(navigator.userAgent) && !window.MSStream;
if(iOS) {
    _$el.css({
        transform: 'translate(' + distanceX + 'px, ' + distanceY + 'px)',
        '-webkit-transition': '-webkit-transform .3s cubic-bezier(0, 0, 0.25, 1)',
        transition: '-webkit-transform .3s cubic-bezier(0, 0, 0.25, 1)',
        transition: 'transform .3s cubic-bezier(0, 0, 0.25, 1)',
        transition: 'transform .3s cubic-bezier(0, 0, 0.25, 1), -webkit-transform .3s cubic-bezier(0, 0, 0.25, 1)'
    });
} else {
    _$el.css({
        left: distanceX + 'px',
        top: distanceY + 'px'
    });
}
```

And that works on iOS, Android and Desktop.

**Comment by makshh** [comment] 2016-09-26 19:55
For me (macOS Sierra):

Translate:

Good: Firefox, Safari, iOS
Bad: Chrome, Opera

Left, top:

Good: Chrome, Opera, Firefox
Bad: **Safari, iOS**

So the issue is for Safari too (with current solution).

For now I can't test on Windows.

**Comment by sachinchoolur** [comment] 2016-09-27 08:15
Thank you guys. 
I am currently on vacation. I'll check this code on all devices once I'm back

**Comment by sachinchoolur** [comment] 2016-12-11 17:27
Hi Guys,
I'm really sorry for the delayed response. I've been super busy lately. 

For me, the issue was happening only on chrome v53 when is use CSS transform. It was working fine when I use CSS left property. 
I've released a new version of [lg-zoom](https://github.com/sachinchoolur/lg-zoom) with a new setting `useLeftForZoom` - If the value of `useLeftForZoom` is true CSS left property will be used for animation. Otherwise , CSS transform will be used. It is true by default on chrome V53 and false on all the other browsers.

Please use the latest version of [lg-zoom](https://github.com/sachinchoolur/lg-zoom) and `lightgallery.css`. Also please let me know if the problem persists.

**Closed by sachinchoolur** 2016-12-11 17:27 UTC
