### ISSUE TITLE
"lg-slide" transitions not working in Safari on macOS and iOS

### ISSUE THREAD

**Issue by wwwonka** [sachinchoolur/lightGallery#1081] opened 2021-07-05 06:40 UTC
setting the transition mode to "lg-slide" works as expected in Chrome and Firefox but not in Safari and iOS; instead it just fades out and fades in rapidly...

Here is a screen recording of the lightgallery.js website in Firefox (89.0.2), with the desired behaviour:

https://user-images.githubusercontent.com/16738328/124427897-019f7080-dd3a-11eb-94cc-4219088690a5.mp4

And here is the same page in Safari:

https://user-images.githubusercontent.com/16738328/124427996-24ca2000-dd3a-11eb-97d4-a57ac782108e.mp4

Tested in Safari 12.1.2 on macOS Mojave 10.14.6 and on iOS 13.

**Comment by sachinchoolur** [comment] 2021-07-05 10:13
This is really strange. Works perfectly on Safari 14. 

Is this happening on the demo website? https://www.lightgalleryjs.com/demos/transitions/

**Comment by wwwonka** [comment] 2021-07-05 23:15
Yes. Just like on the mac:

https://user-images.githubusercontent.com/16738328/124523463-2b51a980-ddc5-11eb-9653-8a2264d6313f.mov

**Comment by sachinchoolur** [comment] 2021-07-06 17:09
Thanks for the video. I can confirm this is happening on older versions of Safari. Looks like some tiny CSS inheritance issue
I'll try to push a fix by tomorrow

**Comment by sachinchoolur** [comment] 2021-07-07 17:44
Hey @wwwonka,

The issue has been fixed in version 2.1.8. The transition-timing function was not getting inherited on safari 12. It was working fine earlier

**Closed by sachinchoolur** 2021-07-07 17:44 UTC

**Comment by wwwonka** [comment] 2021-07-08 00:21
It now works perfectly fine. Awesome.
The only changes you did were in the CSS basically, right?

Anyhow, big cheers to you @sachinchoolur. The fix came in real quick..!

**Comment by sachinchoolur** [comment] 2021-07-08 02:59
Yes, Adding a transition fixes the issue.

**Comment by wwwonka** [comment] 2021-07-08 18:52
Yes.. So the transition works fine on all browsers now but I've been experiencing a weird "jump-cut" issue during the zoom transition when clicking the thumbnail since I updated both the CSS and JS to 2.1.8 

https://user-images.githubusercontent.com/16738328/124975317-e82d4b80-dffb-11eb-9c3f-0a6778b5de78.mp4

This same behaviour happens on iOS once again.

**Comment by wwwonka** [comment] 2021-07-08 19:28
I've been testing it several times, the pattern is: first time I click, the transition always occurs as expected, then once the gallery is closed and reopened again, this glitch occurs. Any idea what might be causing that?
