### ISSUE TITLE
Lighgallery doesn't work for me

### ISSUE THREAD

**Issue by Alexandra667** [sachinchoolur/lightGallery#644] opened 2017-08-18 13:14 UTC
Hello,
I tried to implement lightgallery into my web - it's really nice and exactly what I have in mind for my gallery.
Even after hours of trying to get this to work I was not succesful.

Even created separate test page to test it, but it doesn't work at all... Am I missing something?

`<html>
	<head>
		<title>Title</title>
        <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<link href="resources/images/icons/favicon.ico" rel="icon" type="image/ico">
		<link href="css/animate.css" rel="stylesheet">
		<link href="css/lightgallery.css" rel="stylesheet" >
		<link href="css/lg-transitions.css" rel="stylesheet">

	</head>

	<body bgcolor="#ffffff" text="#000000">

        <script src="jquery-3.1.1.min.js"></script>
		<script src="js/lightgallery.min.js"></script>
        <script src="js/transition.js"></script>

		<script src="js/lg-autoplay.min.js"></script>
		<script src="js/lg-fullscreen.min.js"></script>
		<script src="js/lg-hash.min.js"></script>
		<script src="js/lg-pager.min.js"></script>
		<script src="js/lg-share.min.js"></script>
		<script src="js/lg-thumbnail.min.js"></script>
		<script src="js/lg-video.min.js"></script>
		<script src="js/lg-zoom.min.js"></script>

				<div id="anchor-tag">
					<a href="../image-storage/artists/gg1001004_01.jpg">
						<img src="../image-storage/artists/gg1001004_01.jpg" width="" height="200" />
					</a>

					<a href="../image-storage/artists/gg1001004_02.jpg">
						<img src="../image-storage/artists/gg1001004_02.jpg" width="" height="200" />
					</a>

					<a href="../image-storage/artists/gg1001004_03.jpg">
						<img src="../image-storage/artists/gg1001004_03.jpg" width="" height="200" />
					</a>

					<a href="../image-storage/artists/gg1001004_04.jpg">
						<img src="../image-storage/artists/gg1001004_04.jpg" width="" height="200" />
					</a>

					<a href="../image-storage/artists/gg1001004_05.jpg">
						<img src="../image-storage/artists/gg1001004_05.jpg" width="" height="200" />
					</a>

					<a href="../image-storage/artists/gg1001004_06.jpg">
						<img src="../image-storage/artists/gg1001004_06.jpg" width="" height="200" />
					</a>

					<a href="../image-storage/artists/gg1001004_07.jpg">
						<img src="../image-storage/artists/gg1001004_07.jpg" width="" height="200" />
					</a>

					<a href="../image-storage/artists/gg1001004.jpg">
						<img src="../image-storage/artists/gg1001004.jpg" width="" height="200" />
					</a>
				</div>

		<script type="text/javascript">
			$('#anchor-tag').lightGallery();
///			$(document).ready(function() {
///				$("#lightgallery").lightgallery(); 
///			});
		</script>

	</body>
</html>`

**Comment by sachinchoolur** [comment] 2017-08-19 16:02
Hey @Alexandra667,

Everything seems to be ok in your code. It would be helpful if you could please provide a jsfiddle demo or send me the whole project folder.
Here is the working demo for your reference - https://codepen.io/sachinchoolur/pen/QjLNMM

**Comment by Jhony-Reyes** [comment] 2017-10-25 16:37
@Alexandra667 
I think the problem is in the src of each script, should be something like this: https://cdn.jsdelivr.net/npm/lightgallery@1.6.3/dist/js/lightgallery.js

In addition the scripts should be placed just before closing the </body>
including the Lightgallery initialization script

**Closed** 2017-10-26 02:03 UTC

**Comment by Valariusii** [comment] 2023-07-07 03:00
@Alexandra667 Hi there. Random comment, but I imagine you are the same Alexandra that commented on the AoC Kickstarter. I see you are looking to get a refund unsuccessfully. If you don't want it anymore I am more than willing to buy it off your hands. Just hit me up on discord - rhys5800, if you are interested.
