### ISSUE TITLE
Error when closing gallery

### ISSUE THREAD

**Issue by OXAYAZA** [sachinchoolur/lightGallery#849] opened 2018-12-24 09:28 UTC
In Chrome 71, exception is thrown when invoking `document.exitFullscreen()` while not in full-screen mode.
https://github.com/jpilfold/ngx-image-viewer/issues/23#issuecomment-446899261

**Comment by sanastasiou** [comment] 2018-12-29 22:59
I can confirm. Exact same bug.

**Comment by sanastasiou** [comment] 2018-12-29 23:00
Will fix it locally with one of the mentioned workarounds.

**Comment by aj1991** [comment] 2019-01-09 14:39
Same here. Any plans to fix this? :)

**Comment by zslabs** [comment] 2019-01-17 02:07
@sachinchoolur It looks like https://github.com/jpilfold/ngx-image-viewer/issues/23 had some potential fixes for this issue.

**Comment by stat1x** [comment] 2019-01-24 15:35
Same here.

**Comment by stevepcooke** [comment] 2019-01-30 21:04
I get this error sent to the DOM when closing the full screen view in Chrome

Uncaught (in promise) TypeError: Document not active
    at Fullscreen.exitFullscreen 
(lg-fullscreen.js:75)
    at Fullscreen.destroy (lg-fullscreen.js:107)
    at Function.<anonymous> (lightgallery.js:1311)
    at Function.each (jquery-3.1.1.min.js:2)
    at Plugin.destroy (lightgallery.js:1309)
    at HTMLSpanElement.<anonymous> (lightgallery.js:1244)
    at HTMLSpanElement.dispatch (jquery-3.1.1.min.js:3)
    at HTMLSpanElement.q.handle (jquery-3.1.1.min.js:3)

**Comment by stevepcooke** [comment] 2019-01-30 21:50
I have fixed this issue by editing the  lightgallery-all.js  file changing line 1645  
From :   if (document.exitFullscreen) {
To:  if (document.fullscreenElement) {

**Comment by aj1991** [comment] 2019-01-31 17:03
Fixing this problem in source files seems not to be the right solution

**Comment by hugolantaume** [comment] 2019-02-07 19:54
Same here.

**Comment by zslabs** [comment] 2019-02-07 19:56
If someone can create a PR with the fix; this can most likely get fixed a lot sooner.

**Comment by elemis** [comment] 2019-02-13 10:45
Same here

**Comment by mafh** [comment] 2019-02-17 14:42
+1

**Closed** 2019-02-19 03:38 UTC

**Comment by sachinchoolur** [comment] 2019-02-19 03:55
Guys, Really sorry for the delayed response. The issue has been fixed.

**Comment by yoldar** [comment] 2019-02-19 11:27
> Guys, Really sorry for the delayed response. The issue has been fixed.

Do not forget to add lib to NPM

<img width="879" alt="screen shot 2019-02-19 at 5 26 01 pm" src="https://user-images.githubusercontent.com/1597578/53011841-8fc97380-346b-11e9-9937-0f33dd1f9bcb.png">

**Comment by sanket-webmavens** [comment] 2019-11-22 05:45
> +1

It seems like the error still occurs if we use the all.min.js from dist/js.

**Comment by idahopotato1** [comment] 2021-04-18 19:42
You can open the all.min.js and search for prototype.exitFullscreen=function 
and then change the {document.exitFullscreen?  
to {document.fullscreenElement? 

That fixes it.

**Comment by harsh-webmavens** [comment] 2021-09-10 09:05
After doing that full screen function doesn't working properly
