### ISSUE TITLE
Image flickered when opening in gallery 

### ISSUE THREAD

**Issue by dharmendrasingh88** [sachinchoolur/lightGallery#1200] opened 2021-11-06 04:22 UTC
Hi 
When I am trying to open an image from the gallery it is flickering can you please review the attached video.
[Click me for video](https://drive.google.com/file/d/1OQTT3_1PbK-mVB-c_HBZn8B5FvODjiI8/view?usp=sharing)
 Might be I am missing any setting. here is my setting,
` let lightGalleryPlugin=lightGallery($imageBankGallery, {
        selector: '.bankItem',
        
        plugins: [lgAutoplay, lgZoom, lgThumbnail, lgFullscreen, lgShare, lgRotate, lgVideo],
                        mobileSettings: {
                        controls: false,
                        showCloseIcon: false,
                        download: false,
                            rotate: false,
                        fullScreen:false
                    },
        speed: 400,
        pinterest: false,
       licenseKey: '0000-0000-000-0000',
    });`

**Comment by sachinchoolur** [comment] 2021-11-06 04:30
Looks like you are using the wrong `data-lg-size` attribute values. 

**Docs** 
- https://www.lightgalleryjs.com/docs/getting-started/#the-markup
- https://www.lightgalleryjs.com/docs/settings/#zoomFromOrigin

Please provide your website URL if this doesn't work for you. I'll suggest the correct values

**Comment by sachinchoolur** [comment] 2021-11-12 07:44
Closing.. Hope the issue is resolved

**Closed by sachinchoolur** 2021-11-12 07:44 UTC

**Comment by dharmendrasingh88** [comment] 2021-11-13 12:51
> Looks like you are using the wrong `data-lg-size` attribute values.
> 
> **Docs**
> 
> * https://www.lightgalleryjs.com/docs/getting-started/#the-markup
> * https://www.lightgalleryjs.com/docs/settings/#zoomFromOrigin
> 
> Please provide your website URL if this doesn't work for you. I'll suggest the correct values

Here is the url  https://development.ems.se/om-oss/bildbank/
