### ISSUE TITLE
Close dynamic lightgallery with back button (dynamic + hash plugin incompatibility)

### ISSUE THREAD

**Issue by Meru** [sachinchoolur/lightGallery#1226] opened 2021-12-09 13:23 UTC
Dynamic lightgallery seem to be incompatible with Hash plugin. On mobile, closing stuff is usually performed with "back" button. This results in a non-intuitive behavior that the page containing lightgallery is whatever swapped to the previous page in history or browser is being closed completely, if you opened page link from something like Messenger.
Before you'll say that such issue was already reported, yes it was (https://github.com/sachinchoolur/lightGallery/issues/302), but I don't believe it was resolved. Plus I believe any workaronds that were posted in it are true for lightgallery 1.x and not 2.x because they do mention jQuery.

What I want to achieve:
For example in this case https://codepen.io/sachinchoolur/pen/vYmEyRE
I want to be able to close any of the three galleries by pressing browser back button.
Note that in my personal case i do not want to cycle through any previously viewed images before closing the gallery, but other people may expect this to happen as well.

**Comment by sachinchoolur** [comment] 2021-12-18 11:57
Added to 2.6.0 release checklist 👍🏻

**Comment by Meru** [comment] 2021-12-19 22:11
> Added to 2.6.0 release checklist 👍🏻

thank you! that would be really awesome!

**Comment by Sherlock1979** [comment] 2022-02-16 23:15
I agree with @Meru . Pressing the back button is so natural on phones and the expected behaviour is to close the gallery. At the moment the back button navigates back from the whole website which is really annoying. @sachinchoolur thanks for looking into it. Hope it will be released soon.

Meanwhile, is there any workaround to get the expected behaviour of the back button?

Cheers,
David

**Comment by Sherlock1979** [comment] 2022-02-16 23:19
#1014 seems to be the same (or very similar) request.

**Closed** 2022-04-25 17:11 UTC
Labels: v1
