### ISSUE TITLE
Closing Gallery on Mobile by tapping black space

### ISSUE THREAD

**Issue by tragx** [sachinchoolur/lightGallery#619] opened 2017-06-26 18:57 UTC
I recently was able to modify **lightgallery.js** to allow closing of galleries by clicking the black space with the following code. I added it within the function: **Plugin.prototype.closeGallery = function() {}**

Here is my code:
			
            _this.$outer.on('touchstart', function(e) {								

				
				var classList = $(e.target).attr('class').split(/\s+/);
				$.each(classList, function(index, item) {
				    //alert(item);
				    if (item == "lg-img-wrap") {
					    _this.destroy();
				    }
				});	
				
											
            });

**Comment by tragx** [comment] 2017-06-26 18:58
Would probably be more efficient by using **.hasClass()** instead of iterating through all of the classes.

**Comment by tragx** [comment] 2017-06-26 19:48
When I attempt to use the following method using the .hasClass function, it does not work, and the gallery will close when attempting to use the navigation.

            _this.$outer.on('touchstart', function(e) {								
                    if (!_this.$outer.hasClass('lg-img-wrap')) {
                        _this.destroy();
                    }												
            });

**Comment by tragx** [comment] 2017-06-26 19:59
Alright, I'm going to stop editing my post, this is the most efficient way, using **.hasClass()** instead of looping:

        _this.$outer.on('touchstart', function(e) {								
                if ($(e.target).hasClass('lg-img-wrap')) {
                    _this.destroy();
                }												
        });

I was mistakenly checking **(!_this.$outer)** instead of **$(e.target)**

**Comment by sachinchoolur** [comment] 2017-07-04 17:05
Closing as the issue is resolved.

**Closed by sachinchoolur** 2017-07-04 17:05 UTC

**Comment by tioseliani** [comment] 2020-10-13 15:39
Can someone step by step explain to me in which file and what to write to close lightgallery on mobile with background touch?
I tried to write this code in main.js file, but it doesn't work.
Plugin.prototype.closeGallery = function () {
    _this.$outer.on('touchstart', function (e) {
        if ($(e.target).hasClass('lg-img-wrap')) {
            _this.destroy();
        }
    });

}

**Comment by tioseliani** [comment] 2020-10-13 15:40
Can someone step by step explain to me in which file and what to write to close lightgallery on mobile with background touch?
I tried to write this code in main.js file, but it doesn't work.
`Plugin.prototype.closeGallery = function () {
_this.$outer.on('touchstart', function (e) {
if ($(e.target).hasClass('lg-img-wrap')) {
_this.destroy();
}
});

}`
