### ISSUE TITLE
Zoom transition issue

### ISSUE THREAD

**Issue by johnmark1215** [sachinchoolur/lightGallery#1085] opened 2021-07-08 19:03 UTC
## Description

Zoom transition issue 

### Steps to reproduce

1- Open any large image
2- At any corner of the image double click using the mouse to zoom in this corner.
3- Close lightGallery
4- Re-open lightGallery and again at any corner of the opened image double click using the mouse to zoom in this corner.
5- By doing step 4 you now zooming the opened image try to drag the image.

### Expected result

You should found that there's no transition happens.

**Comment by sachinchoolur** [comment] 2021-07-09 14:20
Hey @johnmark1215,

I'm not able to reproduce the issue. Could you please record and share a short video?

**Comment by johnmark1215** [comment] 2021-07-09 20:00
Here's the video:
https://streamable.com/10m4ey
Transition issue in the second 10

**Comment by sachinchoolur** [comment] 2021-07-10 02:05
Thanks for the video. But it is not opening for me 
<img width="1370" alt="Screenshot 2021-07-10 at 7 33 53 AM" src="https://user-images.githubusercontent.com/6586706/125148604-3dc73c80-e151-11eb-9017-ad14576ce86b.png">

Could you please attach directly to this thread?

**Comment by johnmark1215** [comment] 2021-07-10 11:13
I can't because the size of the video is more than 10mb
I have uploaded it in Vimeo please try:
https://vimeo.com/573354566

**Comment by sachinchoolur** [comment] 2021-07-10 13:03
Thanks for the video. The issue has been fixed locally. I'm making a few other improvements as well to the zoom module. 
I'll release a new version with the fix ASAP

**Comment by sachinchoolur** [comment] 2021-07-15 16:45
Fixed in https://github.com/sachinchoolur/lightGallery/commit/67e56e392565c1cd43b7bf5c5f616dd9b5af29c0

Will be available in the next version

**Comment by sachinchoolur** [comment] 2021-09-14 13:59
Closing as resolved

**Closed by sachinchoolur** 2021-09-14 13:59 UTC
Labels: v1
